PackageIdentifier: S42yt.FreSH
PackageVersion: 26.11.0
InstallerType: exe
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /silent /user
  SilentWithProgress: /silent /user
UpgradeBehavior: install
ReleaseDate: 2026-08-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/S42yt/FreSH/releases/download/v26.11.0/FreSH-Setup.exe
    InstallerSha256: BA18D6A0A9C19A3ED58E4CF87F12370054612BF2769339EC71E133D020200AE2
ManifestType: installer
ManifestVersion: 1.6.0
