PackageIdentifier: S42yt.FreSH.Portable
PackageVersion: 26.11.0
InstallerType: portable
Commands:
  - FreSH
UpgradeBehavior: install
ReleaseDate: 2026-08-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/S42yt/FreSH/releases/download/v26.11.0/FreSH.exe
    InstallerSha256: 6DB753204F7ED3B7051EB80A76AA490233789C158BE7D1E4729FF5B4FB0219AB
ManifestType: installer
ManifestVersion: 1.6.0
